# map species names to Atlantis codes
key_ak <- data.frame('Species'=c('Pacific cod',
                                 'Alaska plaice',
                                 'ATF',
                                 'Butter sole',
                                 'Dover sole', 
                                 'Dusky rockfish',                   
                                 'English sole',
                                 'Flathead sole',
                                 'Northern Rock Sole',                
                                 'Pollock',
                                 'Rex sole',
                                 'Southern Rock Sole',                
                                 'Starry flounder',
                                 'Yellowfin sole',
                                 'Northern rockfish',                 
                                 'POP',
                                 'Sablefish',  
                                 'Halibut',   
                                 'Giant Grenadier',
                                 'Big skate',  
                                 'Dogfish',   
                                 'Longnose skate',
                                 'Other skate',
                                 'Thornyhead',
                                 'Shortraker rockfish',
                                 'Rougheye and blackspotted rockfish',
                                 'Bigmouth sculpin',
                                 'Great sculpin',
                                 'Plain sculpin',
                                 'Yellow Irish Lord',
                                 'Harlequin rockfish',
                                 'Redstripe rockfish',
                                 'Sharpchin rockfish',
                                 'Silvergray rockfish',
                                 'Redbanded rockfish',
                                 'Yelloweye rockfish'),
                     'Group'=c('Cod',
                               'Flatfish_shallow',
                               'Arrowtooth_flounder',
                               'Flatfish_shallow',
                               'Flatfish_deep',
                               'Rockfish_pelagic_shelf',
                               'Flatfish_shallow',
                               'Flathead_sole',
                               'Flatfish_shallow',
                               'Pollock',
                               'Rex_sole',
                               'Flatfish_shallow',
                               'Flatfish_shallow',
                               'Flatfish_shallow',
                               'Rockfish_slope',
                               'Pacific_ocean_perch',
                               'Sablefish',
                               'Halibut',
                               'Deep_demersal',
                               'Skate_big',
                               'Dogfish',
                               'Skate_longnose',
                               'Skate_other',
                               'Thornyhead',
                               'Rockfish_slope',
                               'Rockfish_slope',
                               'Sculpins',
                               'Sculpins',
                               'Sculpins',
                               'Sculpins',
                               'Rockfish_slope',
                               'Rockfish_slope',
                               'Rockfish_slope',
                               'Rockfish_slope',
                               'Rockfish_demersal_shelf',
                               'Rockfish_demersal_shelf'))

# BC
key_bc <- data.frame('Species'=c('ATF',
                                 'Pollock',
                                 'Halibut',
                                 'Thornyhead',
                                 'Rougheye and blackspotted rockfish',
                                 'POP',
                                 'English sole',
                                 'Southern Rock Sole',
                                 'Pacific cod',
                                 'Sablefish'),
                     'Group'=c('Arrowtooth_flounder',
                               'Pollock',
                               'Halibut',
                               'Thornyhead',
                               'Rockfish_slope',
                               'Pacific_ocean_perch',
                               'Flatfish_shallow',
                               'Flatfish_shallow',
                               'Cod',
                               'Sablefish'))